# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_udpClient(object):
    def setupUi(self, udpClient):
        udpClient.setObjectName("udpClient")
        udpClient.setEnabled(True)
        udpClient.resize(800, 600)
        udpClient.setMinimumSize(QtCore.QSize(800, 600))
        udpClient.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(udpClient)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 461, 331))
        self.groupBox.setObjectName("groupBox")
        self.browser = QtWidgets.QTextBrowser(self.groupBox)
        self.browser.setGeometry(QtCore.QRect(10, 20, 441, 171))
        self.browser.setObjectName("browser")
        self.input = QtWidgets.QTextEdit(self.groupBox)
        self.input.setGeometry(QtCore.QRect(10, 200, 441, 71))
        self.input.setObjectName("input")
        self.send = QtWidgets.QPushButton(self.groupBox)
        self.send.setGeometry(QtCore.QRect(370, 280, 81, 41))
        self.send.setObjectName("send")
        self.file = QtWidgets.QLabel(self.groupBox)
        self.file.setGeometry(QtCore.QRect(90, 280, 201, 30))
        self.file.setObjectName("file")
        self.chooseFile = QtWidgets.QPushButton(self.groupBox)
        self.chooseFile.setGeometry(QtCore.QRect(10, 280, 75, 30))
        self.chooseFile.setObjectName("chooseFile")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(480, 170, 311, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.recentTable = QtWidgets.QTableWidget(self.groupBox_2)
        self.recentTable.setGeometry(QtCore.QRect(10, 20, 291, 151))
        self.recentTable.setAutoScroll(True)
        self.recentTable.setRowCount(0)
        self.recentTable.setObjectName("recentTable")
        self.recentTable.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.recentTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.recentTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.recentTable.setHorizontalHeaderItem(2, item)
        self.recentTable.horizontalHeader().setCascadingSectionResizes(False)
        self.recentTable.verticalHeader().setVisible(False)
        self.recentTable.verticalHeader().setDefaultSectionSize(20)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 360, 781, 211))
        self.groupBox_3.setObjectName("groupBox_3")
        self.log = QtWidgets.QTextBrowser(self.groupBox_3)
        self.log.setGeometry(QtCore.QRect(10, 20, 761, 181))
        self.log.setObjectName("log")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(480, 20, 311, 141))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(20, 20, 50, 20))
        self.label.setObjectName("label")
        self.serverIP = QtWidgets.QLineEdit(self.groupBox_4)
        self.serverIP.setGeometry(QtCore.QRect(80, 20, 121, 20))
        self.serverIP.setObjectName("serverIP")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(210, 20, 25, 20))
        self.label_2.setObjectName("label_2")
        self.serverPort = QtWidgets.QLineEdit(self.groupBox_4)
        self.serverPort.setGeometry(QtCore.QRect(240, 20, 60, 20))
        self.serverPort.setObjectName("serverPort")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 61, 20))
        self.label_3.setObjectName("label_3")
        self.packetLimit = QtWidgets.QLineEdit(self.groupBox_4)
        self.packetLimit.setGeometry(QtCore.QRect(80, 50, 81, 20))
        self.packetLimit.setObjectName("packetLimit")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(170, 50, 35, 20))
        self.label_4.setObjectName("label_4")
        self.apply = QtWidgets.QPushButton(self.groupBox_4)
        self.apply.setGeometry(QtCore.QRect(220, 50, 81, 23))
        self.apply.setObjectName("apply")
        self.recentAnal = QtWidgets.QLabel(self.groupBox_4)
        self.recentAnal.setGeometry(QtCore.QRect(10, 80, 191, 21))
        self.recentAnal.setObjectName("recentAnal")
        self.allAnal = QtWidgets.QLabel(self.groupBox_4)
        self.allAnal.setGeometry(QtCore.QRect(10, 110, 191, 21))
        self.allAnal.setObjectName("allAnal")
        self.reset = QtWidgets.QPushButton(self.groupBox_4)
        self.reset.setGeometry(QtCore.QRect(210, 90, 42, 40))
        self.reset.setObjectName("reset")
        self.quit = QtWidgets.QPushButton(self.groupBox_4)
        self.quit.setGeometry(QtCore.QRect(260, 90, 42, 40))
        self.quit.setObjectName("quit")
        udpClient.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(udpClient)
        self.statusbar.setObjectName("statusbar")
        udpClient.setStatusBar(self.statusbar)

        self.retranslateUi(udpClient)
        QtCore.QMetaObject.connectSlotsByName(udpClient)

    def retranslateUi(self, udpClient):
        _translate = QtCore.QCoreApplication.translate
        udpClient.setWindowTitle(_translate("udpClient", "UDP网络通信客户端 v0.3d"))
        self.groupBox.setTitle(_translate("udpClient", "网络通信"))
        self.send.setText(_translate("udpClient", "发送"))
        self.file.setText(_translate("udpClient", "未选择文件..."))
        self.chooseFile.setText(_translate("udpClient", "选择文件"))
        self.groupBox_2.setTitle(_translate("udpClient", "最近一次通信过程"))
        item = self.recentTable.horizontalHeaderItem(0)
        item.setText(_translate("udpClient", "包编号"))
        item = self.recentTable.horizontalHeaderItem(1)
        item.setText(_translate("udpClient", "大小"))
        item = self.recentTable.horizontalHeaderItem(2)
        item.setText(_translate("udpClient", "状态"))
        self.groupBox_3.setTitle(_translate("udpClient", "运行日志"))
        self.groupBox_4.setTitle(_translate("udpClient", "设置"))
        self.label.setText(_translate("udpClient", "服务器IP"))
        self.label_2.setText(_translate("udpClient", "端口"))
        self.label_3.setText(_translate("udpClient", "包大小限制"))
        self.label_4.setText(_translate("udpClient", "Bytes"))
        self.apply.setText(_translate("udpClient", "应用更改"))
        self.recentAnal.setText(_translate("udpClient", "本次传送 0 个包，重传 0 个包"))
        self.allAnal.setText(_translate("udpClient", "累计传送 0 个包，重传 0 个包"))
        self.reset.setText(_translate("udpClient", "重置"))
        self.quit.setText(_translate("udpClient", "退出"))

